export const GIRIS_YAP =  "GIRIS_YAP" ;
export const GIRIS_YAPILIRKEN_BIR_HATA_OLUSTU =  "GIRIS_YAPILIRKEN_BIR_HATA_OLUSTU" ;
export const CIKIS_YAP =  "CIKIS_YAP" ;
export const CIKIS_YAPILIRKEN_BIR_HATA_OLUSTU =  "CIKIS_YAPILIRKEN_BIR_HATA_OLUSTU" ;
export const KAYIT_OL =  "KAYIT_OL" ;
export const KAYIT_OLURKEN_BIR_HATA_OLUSTU =  "KAYIT_OLURKEN_BIR_HATA_OLUSTU";
export const SET_LOGGED_IN = "SET_LOGGED_IN";
